name: Test Site 5 Ninth
favicon: null
layout_spectrum: 0.5054898441303521
typography_spectrum: 0.4625288201496005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.181358014466241
  lightness: 0.113971758633852
  saturation: 0.6556352591142058
  rhythmicContrast: 0.5471351260785013
purpose: []
